version: '2'

services:

  seleniumhub:
    image: selenium/hub:3.14.0-helium
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 10 
    
  chromenode:
    image: selenium/node-chrome-debug:3.14.0-helium
    ports:
      - 4577
    depends_on:
      - seleniumhub
    environment:
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
      - HUB_HOST=seleniumhub

  
